version: '3.8'

volumes:
  pgdata:

networks:
  pong:
    driver: bridge

services:
  web:
    container_name: server
    build:
      context: ./backend_project
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - pong
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - pong
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
