volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./data/postgres
      o: bind

networks:
  pong:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - pong
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
