volumes:
  sqlite:
    name: sqlite
    driver: local
    driver_opts:
      device: /home/migas/ft_transcendence/data/sqlite
      o: bind
      type: none

services:
  server:
    build:
      context: ./srcs/server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
  sqlite:
    build:
      context: ./srcs/sqlite/
      dockerfile: Dockerfile
    volumes:
    - sqlite:/db