volumes:
  sqlite:
    driver: local
    driver_opts:
      device: ./data/sqlite
      o: bind
      type: none
  public:
    driver: local
    driver_opts:
      device: ./data/public
      o: bind
      type: none

services:
  server:
    build:
      context: ./srcs/server/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - sqlite:/db
      - ./data/public/:/app/data/public/:ro
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite

  user:
    build:
      context: ./srcs/user/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite:/db
      - public:/public
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite

  matches:
    build:
      context: ./srcs/matches/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - sqlite:/db
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite
      - user

  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    volumes:
      - sqlite:/db
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite
  
  game:
    build:
      context: ./srcs/game/
      dockerfile: Dockerfile
    volumes:
      - sqlite:/db
    ports:
      - "9002:9002"
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite

  sqlite:
    build:
      context: ./srcs/sqlite/
      dockerfile: Dockerfile
    volumes:
      - sqlite:/db
      - public:/data/public
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
