services:
  server:
    build:
      context: ./srcs/server/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    # env_file:
    #   - .env
  jwt_token:
    build:
      context: ./srcs/jwt_token
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  # auth:
  #   build:
  #     context: ./srcs/auth
  #     dockerfile: Dockerfile
  # sqlite:
  #   build:
  #     context: ./srcs/sqlite
  #     dockerfile: Dockerfile

networks:
  transcendence:
    driver: brigde