volumes:
  sqlite:
    name: sqlite
    driver: local
    driver_opts:
      device: ./data/sqlite
      o: bind
      type: none

services:
  server:
    build:
      context: ./srcs/server/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite
  user:
    build:
      context: ./srcs/user/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite:/db
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite
  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    volumes:
      - sqlite:/db
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - sqlite
  sqlite:
    build:
      context: ./srcs/sqlite/
      dockerfile: Dockerfile
    volumes:
      - sqlite:/db
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge